<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.18" />
    <PackageReference Include="Hangfire.Core" Version="1.8.18" />
    <PackageReference Include="Hangfire.Dashboard.Basic.Authentication" Version="7.0.1" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.18" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageReference Include="SpecFlow" Version="3.9.74" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cinemate.Repository\Cinemate.Repository.csproj" />
  </ItemGroup>

</Project>
